### ISSUE TITLE
How to setup redirect.center on own server/VPS?

### ISSUE THREAD

**Issue by juno0424** [udleinati/redirect.center#24]
Hi, you've developed a great tool for us. I would like to know how can I install this redirect.center on my own server/VPS/AWS/GCP?

Step by step would be very appreciated 👍 

Cheers!

**Comment by udleinati** [comment]
Hey Juno, all you need to know is inside the file READM.md. 

$ npm install
export FQDN=redirect.center - change to your domain
export PORT=80
export PUBLIC_IP=54.84.55.102 - change to your ip

*.redirect.center CNAME TO redirect.center - change to your dns

$ npm run pm2-start

done. Any problem, let me know.

Regards

**Comment by juno0424** [comment]
Hi Udle,

```
npm ERR! Linux 4.13.0-1011-gcp
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "eslint"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redirect.center@2.0.0 eslint: `eslint src/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the redirect.center@2.0.0 eslint script 'eslint src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redirect.center package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redirect.center
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redirect.center
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/redirect.center/npm-debug.log
npm ERR! Test failed.  See above for more details.
```
I added permanent environment variable as per instructed.

1. Create new instance from Google Cloud Compute (Ubuntu 16.04)
2. Install node.js and npm
3. Set environment variables
4. Install eslint
5. execute npm test failed (log above)

do i need to edit config.js ? 

PS: http and https port are opened.

**Comment by juno0424** [comment]
I got it running! 

Note: Make sure you're running Node.JS 8 instead of 4!
