### ISSUE TITLE
How to redirect from https?

### ISSUE THREAD

**Issue by Vadorequest** [udleinati/redirect.center#26]
I have setup a redirect as follow:
![image](https://user-images.githubusercontent.com/3807458/45741072-f9accb00-bbf6-11e8-95c4-72581d70b183.png)
![image](https://user-images.githubusercontent.com/3807458/45741084-03363300-bbf7-11e8-8554-76efb3bdc367.png)

Basically, I want to redirect all unly.fr to unly.org, wether HTTP, HTTPS, www., etc.

It works fine for this domain:
[http://unly.fr](http://unly.fr)

But it doesn't work for the following:
[https://unly.fr](https://unly.fr)

I wonder what I need to do on my side to setup this properly. I'm using AWS (if that helps).

**Comment by udleinati** [comment]
@Vadorequest, unfortunately, it won't work redirecting https... it happens because of redirect.center doesn't have your certificate to accept https://unly.fr and then direct... I was creating a new service called redirect.pro to solve it but due to the low request, I gave up...

**Comment by Vadorequest** [comment]
Okay, thanks @udleinati anyway, it's not my main use case so I'll live with it!
