### ISSUE TITLE
Redirect to pages like YouTube with ?=

### ISSUE THREAD

**Issue by timhaettich** [udleinati/redirect.center#28]
Please add a function to redirect to pages with an URL like. youtube.com/watch?v=IiO...

(Question Mark and Equal sign)

**Comment by gattoFritto** [comment]
you can do a HTML/PHP redirect else you can use .opts-slash. on youtu.be like youtu.be.opts-slash.[insert video id].redirect.center . Sorry for bad english but i'm italian

**Comment by udleinati** [comment]
@timhaettich You can now use URL parameters, thanks to @mike1808
