### ISSUE TITLE
API endpoint to encode url

### ISSUE THREAD

**Issue by ab-pivot** [udleinati/redirect.center#33]
It would be great to add an API endpoint that could convert URL into CNAME string based on rules from [redirect.service.js](https://github.com/udleinati/redirect.center/blob/master/src/services/redirect.service.js#L27)

**Comment by MathewBoyles** [comment]
@ab-pivot I've created something like this

[https://github.com/MathewBoyles/redirect.center-generator](https://github.com/MathewBoyles/redirect.center-generator)

**Comment by udleinati** [comment]
@MathewBoyles cool, I'm going to add something like that soon. Thanks.

**Comment by udleinati** [comment]
Sorry for the long delay. This project was in standby for a while. Thanks to @mike1808, this feature is now available on our website. Not an API but a javascript converter.
