### ISSUE TITLE
.opts-slash. converts to .opts-dash.

### ISSUE THREAD

**Issue by timhaettich** [udleinati/redirect.center#34]
I have the following URL in my DNS setting:
youtu.be.opts-slash.qxPCUvE7wBE.redirect.center

This redirects me to
http://youtu.be.opts-dash.qxpcuve7wbe/

instead of 
http://youtu.be/qxpcuve7wbe/
like it should be.

**Comment by udleinati** [comment]
@timhaettich were you able to solve it? Please check what you have on your dns, I tried to simulate here and didn't work. If possible, send me the cname that's redirecting to youtube.
