### ISSUE TITLE
Use Let's Encrypt to support HTTPS

### ISSUE THREAD

**Issue by fregante** [udleinati/redirect.center#35]
Current configuration, it redirects any subdomain to https://twitter.com/fregante.

```
* CNAME twitter.com.opts-slash.fregante.opts-https.redirect.center
```

It works when visiting `http` URLs: (example using httpie)

```
❯ http http://wildcard.bfred.it
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 62
Content-Type: text/plain; charset=utf-8
Date: Fri, 26 Jul 2019 11:00:31 GMT
Location: https://twitter.com/fregante
Vary: Accept
X-Powered-By: Express

Moved Permanently. Redirecting to https://twitter.com/fregante
```

But it doesn't when the URL is already HTTPS:

```
❯ http https://wildcard.bfred.it
http: error: Request timed out (30s).
```

Nowadays this can be done via Let's Encrypt, at least for requests following the first one (since it might take more than a few seconds to validate the domain)

**Comment by MrSpinne** [comment]
Great idea but without https it's unusable for me!

**Comment by twieren** [comment]
Same problem here, http redirect works fine, https does not work.

**Comment by udleinati** [comment]
Unfortunately redirecting using https doesn't work because redirect.center needs the certificate for each domain, using DNS only it's not possible. I might create this possibility in the future but it needs to be a different project and might have some costs.

**Comment by theel0ja** [comment]
My experimental instance at https://redirect.lelux.fi/ supports HTTPS (uploading scripts&haproxy config soon).

It generates certificates (using certbot) & deploys the certificates to my HAProxy instance automatically, triggered from loading the domain in a browser.

**Please do not point wildcards though, as it would get me ratelimited from LE's API when many of those subdomains are accessed by some scanner bots**

And most of the subdomains would not work before a cert has to be generated, so users would get only TLS connection errors which would degrade the experience.

**Comment by theel0ja** [comment]
Code available here:

https://github.com/theel0ja/redirect.center-cert-ask

Uses Caddy for on-demand HTTPS and PHP script to validate CNAME (optional)

**Comment by tmackay-cenet** [comment]
We can frontend with _nginx_ to add HTTPS. Let's Encrypt also supports wildcard domains which seem to work with the browsers I have tried. If hostname is _redirect.center_, obtain a certificate for _*.center_ to cover all subdomains. I have also successfully frontended with AWS CloudFront using a wildcard alternate domain.

```
#!/bin/bash
sudo apt-get install -y nginx python3-certbot-nginx

# wildcard cert requires DNS validation (can be scripted using https://github.com/acmesh-official/acme.sh)
sudo certbot --server https://acme-v02.api.letsencrypt.org/directory -d *.center --agree-tos --email bob@example.com --manual --preferred-challenges dns-01 certonly

cat <<EOT > /etc/nginx/sites-available/default
server {
  listen 80;
  server_name redirect.center;
  location / {
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:3000;
  }
}
server {
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/center/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/center/privkey.pem;
  server_name redirect.center;
  location / {
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:3000;
  }
}
EOT

sudo systemctl restart nginx
```
