### ISSUE TITLE
Add .opts for underscore

### ISSUE THREAD

**Issue by stephanlachnit** [udleinati/redirect.center#46]
I want to redirect to a website that has an underscore in it's link, but that's not possible with redirect.center. redirect.center will just spit the underscore out again (`https://example.com/some_site` gets converted to `example.com.opts-slash.some_site.opts-https.redirect.center.`). However, I can't enter underscores for CNAME entries. It would be nice, if they could be converted similar to the the equal sign (e.g. with `.opts-us`).

**Comment by udleinati** [comment]
@stephanlachnit is this problem still happening? I rewrote the code on top of nestjs and did some fixies. You can now use base32 encode replacing = by - and use any kind of content.

**Comment by lordofire** [comment]
@udleinati Seems like the redirection for `app.testdomain.com.opts-slash.abc_test.opts-slash.test123.redirect.center.` could not redirect to `http://app.testdomain.com/abc_test/test123` now after the change, and I got the error like the following:

```
{"statusCode":500,"message":"NOTADOMAIN: The record on the host <our domain> is not valid.","error":"Internal Server Error"}
```

Can you help check? Thanks. (Just note that I have intentionally blurred the domain names above)

**Comment by udleinati** [comment]
@lordofire it's working now, try again.
