### ISSUE TITLE
Wrong bind file ?

### ISSUE THREAD

**Issue by malutanpetronel** [udleinati/redirect.center#60]
I try to use your service to redirect a client domain to a url and I have in my DNS 

; BIND data file
@               IN      A       54.84.55.102
redirect termosuflante.ro IN CNAME eurokomax.ro.opts-slash.termosuflante-aeroterme.redirect.center.

Please tell me what I am missing here ?

**Comment by udleinati** [comment]
@malutanpetronel sorry for my delay to reply. It's correct! nothing is wrong. you can test this redirect here: http://test2.nati.biz. Check if you are not accessing it using httpS://.
